name: Fakt nevim


on: 
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "SDK Release Version (e.g. v2.0.1)"
        required: true
        


jobs:
  Cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create text file
        run: echo "Sample text>"$(date +"%T") > file.txt
      - name: cache text file
        id: cache-file
        uses: actions/cache@v3
        with:
          path: ./file.txt
          key: SDK-${{inputs.version}}-build
  Test:
    needs: [Cache]
    uses: ./.github/workflows/test.yml
    with:
      cacheKey: SDK-${{inputs.version}}-build