name: "Commit test"


on:
  workflow_dispatch:

env: 
  PUBLISHER: 'appDfpTestMonitoring'

jobs:

  testA:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Commit and push" > hello.txt
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Test app :${{ env.PUBLISHER }}"