name: "Cron test"


on:
  workflow_dispatch:
  schedule:
    - cron: '0,30 * * * *'
    - cron: '*/5 * * * *'

env: 
  PUBLISHER: 'appDfpTestMonitoring'

jobs:

  testA:
    if: github.event.schedule == '0,30 * * * *'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello cron! A" > hello.txt
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Apply config version A (${{ env.PUBLISHER }})"


  testB:
    if: github.event.schedule == '*/5 * * * *'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello cron! B" > hello.txt
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Apply config version B (${{ env.PUBLISHER }})"
