name: "Cron test"


on:
  schedule:
    - cron: '0,30 * * * *'
    - cron: '15,45 * * * *'

jobs:

  testA:
    if: github.event.schedule == '0,30 * * * *'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello cron! A"

  testB:
    if: github.event.schedule == '0,30 * * * *'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello cron! B"
